services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress 
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/lvan-slu/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  redis:
    build: requirements/redis
    container_name: redis
    env_file: .env
    networks:
      - inception
    ports:
      - "6379:6379"
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
  ftp:
    container_name: ftp
    build: requirements/ftp
    env_file: .env
    ports:
      - "21:21"
      - "${FTP_PASV_MIN_PORT}-${FTP_PASV_MAX_PORT}:${FTP_PASV_MIN_PORT}-${FTP_PASV_MAX_PORT}"
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress 
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  static-site:
    container_name: static-site
    build: requirements/static-site
    ports:
      - "8080"
    volumes:
      - /home/lvan-slu42/Documents/Inception/srcs/requirements/static-site/dist:/var/www/static-site
    networks:
      - inception
  adminer:
    container_name: adminer
    build: requirements/adminer
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - /home/lvan-slu/data/mariadb:/var/lib/html
networks:
  inception:
    driver : bridge
