services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  redis:
    build: requirements/bonus/redis
    container_name: redis
    env_file: .env
    networks:
      - inception
    ports:
      - "6379:6379"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    env_file: .env
    ports:
      - "21:21"
      - "${FTP_PASV_MIN_PORT}-${FTP_PASV_MAX_PORT}:${FTP_PASV_MIN_PORT}-${FTP_PASV_MAX_PORT}"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  static-site:
    container_name: static-site
    build: requirements/bonus/static-site
    ports:
      - "8080"
    volumes:
      - ./requirements/bonus/static-site/dist:/var/www/static-site
    networks:
      - inception
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000"
  portainer:
    build: requirements/bonus/portainer/.
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      inception:
    restart: always
networks:  
  inception:
    driver : bridge
volumes:
  portainer_data:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/lvan-slu/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lvan-slu/data/wordpress
      o: bind