services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/lvan-slu/data/wordpress:/var/www/wordpress 
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/lvan-slu/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  redis:
    build: requirements/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
networks:
  inception:
    driver : bridge
